### ISSUE TITLE
AttributeError: module 'keras.engine' has no attribute 'Layer'

### ISSUE THREAD

**Issue by vasanth26code** [BupyeongHealer/Mask_RCNN_tf_2.x#1]
when i run the model.py and demo i get this error

**Comment by farcaz** [comment]
@vasanth26code 
The keras 2.x version doesn't support keras.engine. You can solve this by following the instruction below:
Change the occurrences of 'KE.Layer' with 'keras.layers.Layer' in 'model.py'.
Thank you.

**Comment by vasanth26code** [comment]
the error is cleared bro thank you...can you please give instruction to get output of mrcnn implementation after cloning this repo..
im new here and will be useful for my project.... thankss

**Comment by farcaz** [comment]
@vasanth26code Please close this issue and create a new one with more details of the problem/errors you are facing.
Thank you.

**Comment by BupyeongHealer** [comment]
@farcaz Thank you for answering.
