### ISSUE TITLE
 name 'modellib' is not defined

### ISSUE THREAD

**Issue by vasanth26code** [BupyeongHealer/Mask_RCNN_tf_2.x#2]
Create Model and Load Trained Weights
# Create model object in inference mode.
model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)
​
# Load weights trained on MS-COCO
model.load_weights(COCO_MODEL_PATH, by_name=True)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-138183a2a830> in <module>
      1 # Create model object in inference mode.
----> 2 model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)
      3 
      4 # Load weights trained on MS-COCO
      5 model.load_weights(COCO_MODEL_PATH, by_name=True)

**NameError: name 'modellib' is not defined**
@farcaz 
can any 1 help resolve this issue i have all the dependencies installed

**Comment by farcaz** [comment]
This seems you have an improper import in your detector(e.g. baloon.py) script.
Please locate the model.py file from the project folder(eg. /Mask_RCNN_tf_2x/mrcnn) and properly import it as below:
<from mrcnn import model as modellib, utils>

**Comment by vasanth26code** [comment]
Much thanks
