### ISSUE TITLE
Your repo is listed as "official" on Arxiv and paperswithcode

### ISSUE THREAD

**Issue by georggrab** [BupyeongHealer/Mask_RCNN_tf_2.x#3]
Hi, this repository is listed as the official (Author's) implementation of Mask-RCNN, but it is not - this is a fork of the Matterport implementation. Perhaps you could take steps to remove your repository from being listed there.

https://arxiv.org/abs/1703.06870
https://paperswithcode.com/paper/mask-r-cnn

**Comment by BupyeongHealer** [comment]
First of all, thank you for letting me know this.

Actually, I heard this part through my acquaintances and asked for correction.
Currently, it has been modified to the official code.
Have a nice day!

Thank you.
